### ISSUE TITLE
Expose ports in all the Docker Images

### ISSUE THREAD

**Issue by dmoranj** [Bitergia/fiware-chanchan#3]
Current Docker images don't expose any port, so it forces the user to retrieve the private IP of the container in order to connect to the deployed image. It will be easier for the user of individual Docker images to have the useful ports exposed, so they can run the images with the automatic port mapping (e.g.: if a user is executing Docker in a remote server, the ideal way to connect to a Deployed Keystone image would be through the 5000 port of the remote server itself, instead of an internal IP of the Docker image).

**Comment by dmabtrg** [comment]
We usually do that when creating the containers, but you're right, it should also be on the images.  I'm adding that now.

**Comment by dmabtrg** [comment]
New builds of the images should be available shortly on docker hub.
